### ISSUE TITLE
master-SNAPSHOT: Calling fluent API of View.newView().add() fails with NullPointerException

### ISSUE THREAD

**Issue by DonReeal** [baratine/baratine#1]
Hey guys,

I've been experimenting with your master branch for a bit now.

Currently this line gives me a NPE:
` ViewBuilder loginsite = io.baratine.web.View.newView("login.jade").add(CSRFToken.FORM_NAME, csrfToken);`

Workaround - kind of unintuitive:
`ViewBuilder loginsite = io.baratine.web.View.newView("login.jade");
loginsite.map().put(CSRFToken.FORM_NAME, csrfToken);`
 

The underlying map does not get initialized when calling the Builder Method add()

Regards
donreeal

**Comment by carojkov** [comment]
Fixed in 1.0.1
